birthday1 = input('Enter the first persons birthday: ')
birthday2 = input('Enter the second persons birthday: ')
birthday3 = input('Enter the third persons birthday: ')
birthday4 = input('Enter the fourth persons birthday: ')
birthday5 = input('Enter the fifth persons birthday: ')