name = input('Enter your name: ')
age = int(input('Enter your age: '))
height = float(input('Enter your height: '))
hungry = bool(input('Are you hungry? (True/False): '))
print(f'Hello {name}. You are {age} years old. You are {height} tall. It is {hungry} that you are hungry.')
print(f'The type of name is {type(name)}')
print(f'The type of age is {type(age)}')
print(f'The type of height is {type(height)}')
print(f'The type of hungry is {type(hungry)}')
